### ISSUE TITLE
logo contribution

### ISSUE THREAD

**Issue by reallinfo** [andreyvpng/lifelog#1]
Hello @andreyvpng i guess this repository doesn't have a logo yet.  I designed a logo for this repo.

![1](https://user-images.githubusercontent.com/36298335/46821298-ee316780-cd90-11e8-858e-39be3469efb6.jpg)

Web-site view;

![2](https://user-images.githubusercontent.com/36298335/46821313-f689a280-cd90-11e8-9b7f-dd5ad5d20370.jpg)

Please tell me what you think about these logos. I will wait for feedback. We can design a logo together. Have a nice day.

**Comment by andreyvpng** [comment]
Thank you very much. It look really good. I want to use this option.

![screenshot_2018-10-12 46821298-ee316780-cd90-11e8-858e-39be3469efb6 jpg jpeg image 2768 x 1120 pixels - scaled 49](https://user-images.githubusercontent.com/14147741/46843525-9b9a8e80-ce16-11e8-8aec-fb6eca2bc5b6.png)

I will change the navbar background to white

![screenshot_2018-10-12 dashboard - life log](https://user-images.githubusercontent.com/14147741/46843587-fb913500-ce16-11e8-8503-c56c80307378.png)

I need to ask you something. Can you send these logos in separate files? Can you make a favicon in the shape of a heart(red on a white background), which is in the logo?

It would be amazing. Thanks for your time on my project.

**Comment by andreyvpng** [comment]
@reallinfo ,

> I need to ask you something. Can you send these logos in separate files? Can you make a favicon in the shape of a heart(red on a white background), which is in the logo?
> 
> It would be amazing. Thanks for your time on my project.

**Comment by reallinfo** [comment]
Hey, sorry for the late message. I sent a pr. Also, there is the all files. (favicon etc.) you can use any of them.

https://drive.google.com/open?id=1VlErlOnBHrlgOo98MU1aNSoMV8PRGL8w

**Comment by andreyvpng** [comment]
It's okay. Thank you very much for your help!!
